### ISSUE TITLE
Hello! How can I change the encoding?

### ISSUE THREAD

**Issue by trololo151** [kuper-adrian/statg-bot#1]
Tell me please how to change the encoding, the Russian language is displayed in hieroglyphs

**Comment by trololo151** [comment]
GameStat, Player..�����
�����

**Comment by kuper-adrian** [comment]
Hi, to be honest, I never really thought about encodings or special characters when coding statg-bot, so I can't really anwer your question immediatly. But, if you would like to share the username you used to get these strange results, I will look into it and might be able to find a solution.

**Comment by trololo151** [comment]
I did not understand. What name should I specify? If you change the GametTod to a Russian word in the stats-cmd-handler.js file, then the bot writes instead of Russian words the signs in the discord ??? ???? ???? ????

**Comment by kuper-adrian** [comment]
Ah ok, you are coding yourself not just using the bot, cool. Sadly, I still can't quite follow on what you did and couldn't replicate similar results during some quick testing. What do you mean by "GametTod"? Maybe you could name the exact line you changed and the Russian words you used?

**Comment by trololo151** [comment]
File stats-cmd-handler.js 
            name: 'GameMod',
            value: gameMode,
            inline: true,
I wrote in Russian name: 'Режим'
and in a bot in a discord in the place of my word writes ???

**Comment by kuper-adrian** [comment]
Hm, looks like you are using a text editor which is set to use ANSII encoding. Which editor are you using? Changing the encoding of your text editor to UTF-8 should solve your problem.

**Comment by trololo151** [comment]
haha, actually made notepad++ and it turned out, huh, I'm a fool

**Comment by kuper-adrian** [comment]
Cool, happy to see your problem solved :D Closing this issue then
