### ISSUE TITLE
Remove "Win Points" from match command

### ISSUE THREAD

**Issue by kuper-adrian** [kuper-adrian/statg-bot#14]
Since PUBG api v6.0.0 the `winPoints` and `winPointsDelta` values of the `gameModeStats` property are deprecated and always contain the value 0 (see [here](https://forums.playbattlegrounds.com/topic/294431-version-600-is-live/)). Because of that it's quite pointless to show them on `!statg match` and they should be removed.

**Comment by SubashAravindan** [comment]
I'd like to take this up

**Comment by SubashAravindan** [comment]
So I basically have to remove the values from match-cmd-handler.js and stats-cmd-handler.js alone right? Or should I remove it from match-cmd-handler.test.js too?

**Comment by kuper-adrian** [comment]
Yeah, the values have to be removed from the stats and match command handlers. You might break some unit tests in `match-cmd-handler.test.js` and `stats-cmd-handler.test.js` when doing so, so editing these would be nice too (but it's not necessary).

Thanks for contributing 😃

**Comment by SubashAravindan** [comment]
I'm completely new to open source. So yeah, I'm done with the changes and what should I do now? Should I fork it? Or directly push to a new branch?
Sorry for the noob question

**Comment by kuper-adrian** [comment]
No worries there are no "noob" questions. In fact I'm pretty new to open-source as well, so you're in good company :wink:

To answer your question: The general idea is to fork the repository first. You can think of a fork as a separate "copy" of the repository here on GitHub. In your own fork, you can make your changes on any branch you like (since your fork is your own repository so to speak). When your changes are done, you can go to this repository and open a pull request by clicking on the "pull request" tab and then "New pull request". There you can chose your branch from your own fork which is supposed to be "pulled" to this "main" repository. Then I can look at the changes you made and pull them into this repository.

If you still have questions, you could have a look at some tutorials about [git](https://try.github.io/), [pull requests](https://help.github.com/articles/creating-a-pull-request/) and [contributing to open source](https://opensource.guide/how-to-contribute/). Feel free to ask any remaining questions here.

Good luck and happy Hacktoberfest :+1:

**Comment by SubashAravindan** [comment]
Huge thanks for the guidelines. I've made a pul request  #16
