### ISSUE TITLE
invalid amount of arguments

### ISSUE THREAD

**Issue by trololo151** [kuper-adrian/statg-bot#4]
when registering a user such an error
invalid amount of arguments

!statg unregister•Сегодня в 21:23

**Comment by kuper-adrian** [comment]
The `unregister` command does not take any arguments. That means you only have to type 
```
!statg unregister
``` 
(without any username). 

Any string after the `unregister` part will result in the `invalid amount of arguments` error message.

**Comment by trololo151** [comment]
oy, ty :+1:
