### ISSUE TITLE
Wrong rank/win place when using "!statg match"

### ISSUE THREAD

**Issue by kuper-adrian** [kuper-adrian/statg-bot#9]
The win place of individual players inside the same squad can differ (e.g. when a player dies and his team lives on). Since the bot uses the win place of the first player in the squad on ```!statg match```, this leads to misleading/wrongly displayed ranks.

To fix this, the win place of the entire squad should be used inside ```match-cmd-handler.js``` (check api docs [here](https://documentation.playbattlegrounds.com/en/matches-endpoint.html)).

**Comment by medusalix** [comment]
The rank of the entire squad should be provided by `roster.attributes.stats.rank`, right? I'm not too familiar with PUBG, so I want to make sure I'm seeing this correctly before making a pull request 😃.

EDIT: Seems to be working fine, I'm going for it.

**Comment by kuper-adrian** [comment]
```roster.attributes.stats.rank``` looks good.
